### ISSUE TITLE
switch to arrow-body-style always

### ISSUE THREAD

**Issue by vvo** [algolia/eslint-config-algolia#49]
https://eslint.org/docs/rules/arrow-body-style

Today our eslint transforms:

```js
() => {
  return 'a';
}
```

into:

```js
() => 'a';
```

This becomes annoying when you want to add, a console.log or another step:

```js
() => {
  const i = '2';
  return 'a' + i;
};
```

Then the whole git diff gets broken (instead of a one line change, you get N line changed, N being the number of lines of the single return, can be high in React world (JSX) or with object literals.

I propose to always have braces.

WDYT?

**Comment by Haroenv** [comment]
I think that single lines not having braces is okay, because it would make a lot of simple maps/foreach/whatever a lot simpler. 

Your diff opinion makes sense, but I only use arrows for single line functions because I can then leave out the return and brackets. For bigger functions (that don't need `this` from the parent scope) there's no reason for it to be an arrow function IMO. 

```js
() => 'a';

function appender() {
  const i = '2';
  return 'a' + i;
};
```

Does that make sense?

**Comment by iam4x** [comment]
I had at first the same frustration as you @vvo, hitting save before I put my `console.log`... What I do, for JSX I'll try to put the console.log into it:

```jsx
return (
  <h1>
    {console.log('hello')}
    hello
  </h1>
)
```

And for other functions, I try just to remember to don't hit save before I've done writing my console.log.

In the end, I like this rule, it's just sometime a struggle to remember to don't hit save.

**Comment by vvo** [comment]
> In the end, I like this rule, it's just sometime a struggle to remember to don't hit save.

I really think we should never have to think this way, enforcing braces is plain simple, you can still write on a single line, if you hit save it will reformat BUT the difference is that once formatted this is done, it will never go back again to single line (which is disturbing).

@Haroenv suggestion (big functions = modules or real functions, not arrows) is interesting, wonder if we can enforce this without losing the benefit of arrow methods too

**Comment by Haroenv** [comment]
disadvantage of enforcing it would be that you can't use arrow functions for multi-line functions that need parent scope though, I wonder how it can be enforced, or if it even should be enforced 🤔

**Comment by francoischalifour** [comment]
I'm not sure if this issue is still under consideration but I would strongly go against this rule.

It's fine if the rule sometimes introduces friction during early development, as long as the code is ESLint compliant when it reaches a more stable state.

It would make it really painful to write chainable functions without arrow functions. This reason itself is off-putting to me.

---

Tip for logging something and returning JSX with arrow functions:

```javascript
const MyComponent = props => (
  console.log(props) || <div>Hello</div>
)
```

Will run `console.log()` and return the "Hello" `div` (because the log evaluates to `undefined`).

**Comment by francoischalifour** [comment]
Closing since there are more reasons not to go for this rule for now.

Feel free to reopen if you have other arguments.
